Id: Cloudreve.CloudreveServer
Publisher: Cloudreve
Name: CloudreveServer
Version: 3.0.0
AppMoniker: cloudreve
License: GPL V3
Tags: file, storage
LicenseUrl: https://raw.githubusercontent.com/cloudreve/Cloudreve/master/LICENSE
Installers:
  - Arch: x64
    InstallerType: msi
    Url: https://github.com/cloudreve/Cloudreve/releases/download/3.0.0/cloudreve_3.0.0_windows_amd64.msi
    Sha256: 1df54e3037a24a6e241884ccb145e5c72573264760da3212da9884d3802a4988
    Switches:
        SilentWithProgress: "/passive"
        Silent: "/quiet"